### ISSUE TITLE
Auto-generated Table of Contents

### ISSUE THREAD

**Issue by newsch** [olinlibrary/library-website#1]
After some research it looks like there are a couple of options for generating a Table of Contents for a given page with Jekyll:
- _Javascript_ - parse the DOM once loaded and insert a ToC into the page. [Here's an example](https://github.com/ghiculescu/jekyll-table-of-contents).
  \+ doesn't impact site build process
  \- may impact performance of site
  \- requires JS to be enabled
- _Jekyll plugin_ - add a plugin to the site for creating ToCs. I've [found](https://github.com/toshimaru/jekyll-toc) [two](https://github.com/dafi/jekyll-toc-generator) so far.
  \+ integrated with templating system
  \- unknown performance impact for building site
  \- won't work with certain deployment options that limit plugins (like GitHub Pages)
- _Kramdown_ (the default Markdown Processor) has [built-in functionality](https://kramdown.gettalong.org/converter/html.html#toc).
  \+ doesn't impact site build process
  \+ single tag inserted into `*.md` files
  \- must be purposefully added to every page - no way to set defaults.
  \- impedes writing experience, increases boilerplate and learning curve for writing content
  \- inserted into post content - pulling it out into a navigation bar or header/footer would be a little awkward
- _pure [Liquid](https://github.com/Shopify/liquid)_ - I didn't have any idea on how to create this/if it was even possible but thankfully [someone else already has](https://allejo.io/blog/a-jekyll-toc-without-plugins-or-javascript/).
  \+ doesn't restrict deployment options
  \- may increase build times more drastically than a plugin
  \- not quite as seamless as a plugin

I'm currently leaning towards a Jekyll plugin - deployment through Github Pages or something similar seems unlikely given the current setup of library.olin.edu hosting.

**Comment by SeunginLyu** [comment]
I'm currently experimenting with the jekyll-toc and have created a new branch (seungin/jekyll-toc). I'll keep you updated!

**Comment by SeunginLyu** [comment]
@newsch 
Please checkout this branch (https://github.com/olinlibrary/library-website/tree/seungin/jekyll-toc)[here] to see the TOC demo. I figured that..
+ : this is really easy to setup, doesn't affect the build time that much as expected.
- : we are given very little control of the html template that gets generated by the plugin (can't add classes, or extra heading, so I had to extend the tachyon scss to apply the styles which kinda is cheating and the code can get messy pretty soon)

**Comment by SeunginLyu** [comment]
@newsch @jeffgoldenson 
I finished adding TOC which is completely responsive with pure CSS without any javascript hack.
I'm closing this issue!
